PreCommit:
  ALL:
    on_warn: fail
    exclude:
      - 'spec/fixtures/**/*'
      - 'lib/extensions/**/*'
      - 'docs/**/*'
  Reek:
    enabled: true
    exclude:
      - 'lib/extensions/**/*'
      - 'spec/helpers.rb'
  TrailingWhitespace:
    exclude:
      - 'spec/fixtures/**/*'
