language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnupg

script:
  - bundle exec rspec
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token: 290ad1c84c99c410ae860ba338680533edde491c939cb642770a1d1d944f8c92
