language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnupg

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token: 24e78bcdc41ae2bbc7fdd65e0122325864f318b1b8ccc688bd2bb95c1658aa50
